appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: F6GSlH5bVqhOcKTlvrYofZ42eaYtlAcWO4IwPTnn+Q1IqpaM0d63vZN4ln2W5JCW05fZ2jRZ4VpmBag9GpKHpBdDqZgzaomIoBIPryxkZRuGbBDZUKL+G2DXB0iMq3XWV5M0ZZ6YV4Vn5WIo/+a3vZ9JMvgaCSzBErgXGcPQd33jJhsZ0HB19pQz3z7s8CvkgWeHqmKvOyNSD5hEVBr3RaH9idI9rTGtP0Ny1cGyZU0wyy2J1PsOV3+3ly0nyEEtejb08oL1zMoZVgnUUylHgnyKJYmuh4AtVO4U436O1KbNgXRRfG+9u1d1hfzfZzUirWD94ykBtwauHZKosEuQxDHB21O5Wcd33XXxAdTdSp4sIXvNdCR+heNZnxSCziKHMC9J+gcSUfSSyqXFGIN+rsklWow2s5Pbz/CtrceI13fL+pVjV3ha46Gg7arF0m0QCHE06CdrSpXcTkAgoBfQHYKvbJzDSQExDZYKfTNfaXZKOlZ3SUGfZHKTE1i9v1i75n0YH2V5/QbXXUPSK9V131pgtAx20Xtm6O1UaoOB7ao8vJLxnMsJzzUwrVub3N15PiFJHo/oZmIUbmkjv19bj+6+fxIMCwamt/5ektHwJsuTx9niDsCBMyXrx7/sIEfTGoMYA7kg50I6PUHxv2STtkDt//g+gaCEyxL4362QpPk=
conda_forge_output_validation: true
